--Part 1
	--ID int, Name longtext, EmployerId int
--Part 2
	-- select * from employers where location = "St. Louis";
--Part 3
	--select name,description from skills join jobskills on skills.Id = jobskills.SkillId where JobId is not null order by name asc ;
